digital_inclusion/digital_inclusion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from organization_management import views
from main import urls as main_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("org/", include('organization_management.urls', namespace='orgs')),
    path("accounts/", include('user_management.urls')),
    path("flag/", include('flagging.urls', namespace='flags')),
    path("events/", include('events.urls', namespace='events')),
    path("search/", include('search.urls', namespace='search')),
] + main_urls.urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digital_inclusion/flagging/urls.py
from django.conf.urls import url
from flagging import views
from django.http import HttpRequest

app_name = "flagging"
urlpatterns = [
    url(r'submit/$', views.flag, name="flag"),
]

digital_inclusion/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'about/$', views.about, name="about"),
    url(r'map/$', views.map, name="map"),
    url(r'^$', views.index, name="index"),
]

digital_inclusion/organization_management/urls.py
from django.conf.urls import url
from organization_management import views

app_name = "organization_management"
urlpatterns = [
    url(r'wizard/', views.OrganizationWizard.as_view(), name="wizard"),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_organization, name='edit'),
    url(r'^(?P<pk>[0-9]+)/', views.view_organization, name='view'),    
    url(r'$', views.list_organization, name='index')    
]

digital_inclusion/organization_management/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MinValueValidator
from django.utils.translation import gettext as _
from phonenumber_field.modelfields import PhoneNumberField
# from user_management.models import User
from ckeditor.fields import RichTextField


class Service(models.Model):
    type = models.CharField(max_length=256)
    description = models.TextField(max_length=512)

    def __str__(self):
        return str(self.type)

# Create your models here.


class Organization(models.Model):
    name = models.CharField(max_length=512)
    description = RichTextField(max_length=2048, null=True, blank=True)
    website = models.URLField(max_length=512, null=True, blank=True)
    logo_file = models.ImageField(
        null=True, help_text="Must be smaller than 4MB.")
    banner = models.ImageField(
        null=True, blank=True, help_text="Must be smaller than 10MB.")

    def __str__(self):
        return str(self.name)

    # def __dict__(self):
    #     return {
    #         "name": self.name,
    #         "address": self.address,
    #         "description": self.description,
    #         "website": self.website,
    #         "contact_name": self.contact_name,
    #         "contact_phone": self.contact_phone,
    #         "contact_email": self.contact_email,
    #         "key_employees": self.key_employees,
    #         "logo_file": self.logo_file,
    #         "services": self.services,
    #         "latitude": self.latitude,
    #         "longitude": self.longitude,
    #     }


class Language(models.Model):
    name = models.CharField(max_length=15, db_index=True)

    def __str__(self):
        return self.name


class TrainingProgram(models.Model):
    name = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class Branch(models.Model):
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="branches")
    contact_name = models.CharField(max_length=128)
    contact_phone = PhoneNumberField(blank=True, null=True)
    contact_email = models.EmailField(blank=True, null=True)
    key_employees = ArrayField(models.CharField(
        max_length=512), null=True, blank=True, help_text="Comma seperated list.")
    address = models.CharField(max_length=512)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    services = models.ManyToManyField(
        Service, related_name="organizations", blank=True)
    services_other = ArrayField(models.CharField(
        max_length=256), null=True, blank=True, help_text="Comma seperated list.")
    lab_machine_count = models.IntegerField(
        blank=True, null=True, verbose_name="Number of lab machines", validators=[MinValueValidator(0)])
    public_access = models.CharField(
        max_length=255, default="Yes", blank=True, null=True)
    training_programs = models.ManyToManyField(TrainingProgram, blank=True)
    languages = models.ManyToManyField(Language, blank=True)

    def __str__(self):
        return '%s -- %s' % (self.organization, self.address)


class OpeningHours(models.Model):
    WEEKDAYS = [
        (1, _("Monday")),
        (2, _("Tuesday")),
        (3, _("Wednesday")),
        (4, _("Thursday")),
        (5, _("Friday")),
        (6, _("Saturday")),
        (7, _("Sunday")),
    ]
    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        related_name="hours",
    )
    weekday = models.IntegerField(
        choices=WEEKDAYS,
        null=False,
    )
    from_hour = models.TimeField()
    to_hour = models.TimeField()
    class Meta:
        verbose_name_plural = "Opening Hours"
        ordering = ('branch__organization__name', 'branch__address', 'weekday', 'from_hour')
        unique_together = ('weekday', 'from_hour', 'to_hour')

    def __str__(self):
        return '%s on %s: %s - %s' % (self.branch, self.get_weekday_display(),
                                 self.from_hour, self.to_hour)

digital_inclusion/organization_management/forms.py
from django import forms
from django.forms import inlineformset_factory, formset_factory
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget
from organization_management.models import Organization, Branch, OpeningHours


class BranchForm(forms.ModelForm):
    more_branches = forms.BooleanField(label="Add another branch?", required=False)    
    class Meta:
        model = Branch
        fields = ['address', 'contact_name',
                  'contact_email', 'contact_phone', 'languages', 'services', 'lab_machine_count',  'services_other', 'training_programs']
        labels = {
            'services_other': 'Other services',            
        }
        widgets = {            
            'address': forms.TextInput(attrs={'placeholder': 'Organization address'}),
            'contact_name': forms.TextInput(attrs={'placeholder': 'Name of contact'}),
            'contact_phone': PhoneNumberInternationalFallbackWidget(attrs={'placeholder': 'Phone number of contact', 'type': 'tel'}),
            'contact_email': forms.TextInput(attrs={'placeholder': 'Email of contact', 'type': 'email'}),
            'services': forms.SelectMultiple(attrs={'title':'Choose all that apply...',  'class': 'selectpicker'}),
            'languages': forms.SelectMultiple(attrs={'title':'Choose all that apply...',  'class': 'selectpicker'}),
            'training_programs': forms.SelectMultiple(attrs={'title':'Choose all that apply...',  'class': 'selectpicker'}),
            'lab_machine_count': forms.NumberInput(attrs={'placeholder': '20'}),
        }


class OpeningHoursForm(forms.ModelForm):
    class Meta:
        model = OpeningHours
        fields = ['weekday', 'from_hour', 'to_hour']

HoursFormset = inlineformset_factory(Branch, OpeningHours, form=OpeningHoursForm, extra=1)
class AddOrganizationForm(forms.ModelForm):
    # def clean_contact_phone(self):
    #     contact_phone = self.cleaned_data['contact_phone']
    def clean_logo_file(self):
        image = self.cleaned_data.get('logo_file', False)
        if image:
            if image._size > 4*1024*1024:
                raise forms.ValidationError("Image file too large ( > 4mb )")
            return image
        else:
            raise forms.ValidationError("Couldn't read uploaded image")
    class Meta:
        model = Organization
        fields = ['name', 'description', 'website', 'logo_file', 'banner']
        labels = {
            'website': 'Website URL',
            'logo_file': 'Upload a logo',
            'banner': 'Upload a banner'
        }        
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Organization name'}),
            'address': forms.TextInput(attrs={'placeholder': 'Organization address'}),
            'website': forms.TextInput(attrs={'placeholder': 'http://example.com', 'type': 'url'}),
            'contact_name': forms.TextInput(attrs={'placeholder': 'Name of contact'}),
            'contact_phone': PhoneNumberInternationalFallbackWidget(attrs={'placeholder': 'Phone number of contact', 'type': 'tel'}),
            'contact_email': forms.TextInput(attrs={'placeholder': 'Email of contact', 'type': 'email'}),
            'services': forms.SelectMultiple(attrs={'title':'Choose all that apply...'}),
        }

digital_inclusion/organization_management/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_GET
from organization_management.models import Organization, Branch
from organization_management.forms import AddOrganizationForm, BranchForm, HoursFormset
from django.conf import settings
from django.utils import six
from django.core.files.storage import FileSystemStorage
from formtools.wizard.views import SessionWizardView
import requests
import os


# Create your views here.


def get_coord(address):
    gmaps_api_url = "https://maps.googleapis.com/maps/api/geocode/json"
    resp = requests.get(gmaps_api_url,
                        params={
                            "address": address,
                            "key": settings.GOOGLE_MAPS_API_KEY
                        }).json()
    location = resp["results"][0]["geometry"]["location"]
    return (location["lat"], location["lng"])


@require_GET
def list_organization(request: HttpRequest):
    branches = Branch.objects.all()
    context = {'branches': branches}
    return render(request=request, template_name="list_organizations.jinja2", context=context)


class OrganizationWizard(LoginRequiredMixin, SessionWizardView):
    file_storage = FileSystemStorage(location=settings.MEDIA_ROOT)
    form_list = [AddOrganizationForm, BranchForm]
    template_name = 'create_organization.jinja2'

    def get_form_list(self):
        step = self.storage.current_step
        prev_data = self.get_cleaned_data_for_step(step) or {}
        if prev_data and prev_data.get('more_branches') == True:
            keys = list(self.form_list.keys())
            index = keys.index(step) + 1
            key = "more_branches-{0}".format(index)
            self.form_list[key] = BranchForm
        form_list = super().get_form_list()
        return form_list

    # def get_context_data(self, form, **kwargs):
    #     context = super(OrganizationWizard, self).get_context_data(form, **kwargs)
    #     if type(form) == BranchForm:
    #         context["hours_form"] = HoursFormset()
    #     return context
        
    def done(self, form_list, **kwargs):
        for form in form_list:
            if type(form) == AddOrganizationForm:
                organization: Organization = form.save()
            else:
                branch = form.save(commit=False)
                branch.organization = organization
                lat, lng = get_coord(form.cleaned_data["address"])
                branch.latitude = lat
                branch.longitude = lng
                branch.save()
                form.save_m2m()
        return redirect('orgs:view', pk=branch.pk)


def view_organization(request: HttpRequest, pk=None):
    branch = get_object_or_404(Branch, pk=pk)

    context = {'organization': branch.organization,
               'branch': branch}
    return render(request=request, template_name="view_organization.jinja2", context=context)


@login_required()
@require_http_methods(['GET', 'POST'])
def edit_organization(request: HttpRequest, pk=None):
    organization = get_object_or_404(Organization, pk=pk)
    if request.method == "POST":
        edit_form = AddOrganizationForm(request.POST, instance=organization)
        if edit_form.is_valid():
            organization = edit_form.save()
            return redirect('orgs:view', pk=organization.pk)
    elif request.method == "GET":
        edit_form = AddOrganizationForm(instance=organization)
    return render(request=request, template_name="edit_organization.jinja2",
                  context={'form': edit_form, 'organization': organization})

digital_inclusion/organization_management/templates/add_users.jinja2
{% extends "base.jinja2" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}
{% block style %}
    <style>
        #user_add_form {
            margin-top: 100px;
            clear: both;
        }
        #emailInput{

        }
        #emailInput input{
            float:left;
        }
        #emailInput button{
            float:left;
        }
    </style>
{% endblock style %}
{% block content %}

    <div class="container">
        <h1 class="formtitle">Invite Users</h1>
        {% if errors %}
            <h3 class="errors">
                {{ errors }}
            </h3>
        {% endif %}
        <div>
            <button id="add_user" class="mr-3 btn btn-primary pull-right btn-lg">Add user</button>
            <label for="csv_file">Upload CSV: </label>
            <input id="csv_file" name="csv_file" type="file" value="Upload CSV" accept=".csv"/>
        </div>
        <form id="user_add_form" action="{% url "orgs:wizard" %}" method="POST">
            {% csrf_token %}
            {{ wizard.management_form }}
            <div class="inputs">
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                        <label for="emails[]">User Email:</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" name="emails[]" class="form-control">
                    </div>
                    <div class="col-sm-1">
                        <button type="button" class="btn-secondary btn-sm deleteRow">X</button>
                    </div>
                </div>
            </div>



            <div class="row justify-content-end" style="text-align:center">
                <div class="col-sm-10">
                    <button type="submit" class="form-control btn deca-register deca-light-button">Submit</button>
                </div>
            </div>
        </form>
{#        <button type="submit" id="submitBtn" class="form-control btn btn-block deca-register deca-light-button">Next#}
{#            Step#}
{#        </button>#}

    </div>
{% endblock content %}

{% block scripts %}
    <script>
        function parseCSV(str) {
            var arr = [];
            var quote = false;  // true means we're inside a quoted field

            // iterate over each character, keep track of current row and column (of the returned array)
            for (var row = col = c = 0; c < str.length; c++) {
                var cc = str[c], nc = str[c+1];        // current character, next character
                arr[row] = arr[row] || [];             // create a new row if necessary
                arr[row][col] = arr[row][col] || '';   // create a new column (start with empty string) if necessary

                // If the current character is a quotation mark, and we're inside a
                // quoted field, and the next character is also a quotation mark,
                // add a quotation mark to the current column and skip the next character
                if (cc == '"' && quote && nc == '"') { arr[row][col] += cc; ++c; continue; }

                // If it's just one quotation mark, begin/end quoted field
                if (cc == '"') { quote = !quote; continue; }

                // If it's a comma and we're not in a quoted field, move on to the next column
                if (cc == ',' && !quote) { ++col; continue; }

                // If it's a newline (CRLF) and we're not in a quoted field, skip the next character
                // and move on to the next row and move to column 0 of that new row
                if (cc == '\r' && nc == '\n' && !quote) { ++row; col = 0; ++c; continue; }

                // If it's a newline (LF or CR) and we're not in a quoted field,
                // move on to the next row and move to column 0 of that new row
                if (cc == '\n' && !quote) { ++row; col = 0; continue; }
                if (cc == '\r' && !quote) { ++row; col = 0; continue; }

                // Otherwise, append the current character to the current column
                arr[row][col] += cc;
            }
            return arr;
        }
    </script>
    <script>
        String.prototype.format = function () {
            var i = 0, args = arguments;
            return this.replace(/{}/g, function () {
                return typeof args[i] != 'undefined' ? args[i++] : '';
            });
        };
        var userTemplate = "<div class=\"form-group row\">\n" +
            "                <div class=\"col-sm-2 col-form-label\">\n" +
            "                    <label for=\"emails[]\">User Email:</label>\n" +
            "                </div>\n" +
            "                <div class=\"col-sm-9\">\n" +
            "                    <input type=\"text\" name=\"emails[]\" class=\"form-control\" value=\"{}\">\n" +
            "                </div>\n" +
            "                <div class=\"col-sm-1\">\n" +
            "                    <button type=\"button\" class=\"btn-secondary btn-sm deleteRow\">X</button>\n" +
            "                </div>\n" +
            "            </div>"
        $("#add_user").click(function () {
            $("#user_add_form").append(userTemplate.format(""));
        })
        $('#csv_file').on('change', function () {
            var fileReader = new FileReader();
            fileReader.onload = function () {
                try{
                    var data = fileReader.result;
                    var parsedCSV = parseCSV(data);
                    for(var i = 0; i < parsedCSV.length; i++){
                        $("#user_add_form").append(userTemplate.format(parsedCSV[i][0]));
                    }
                }catch (e) {
                    console.log("file could not be parsed")
                }

            };
            fileReader.readAsText($('#csv_file').prop('files')[0]);
        });
        $("#user_add_form").on("click", ".deleteRow",function(e){
            var $this = $(this);
            var parent = $this.parent().parent();
            parent.remove()
        })
    </script>
{% endblock scripts %}

digital_inclusion/organization_management/templates/create_organization.jinja2
{% extends "base.jinja2" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <div class="container">
        <h1 class="formtitle">Register your Organization</h1>
        <form id="registerForm" method="POST" enctype="multipart/form-data" action="{% url "orgs:wizard" %}">
            {% csrf_token %}
            {{ wizard.management_form | crispy }}
            {% if wizard.form.forms %}
                {{ wizard.form.management_form | crispy }}                
                {% for form in wizard.form.forms %}
                    {{ form  | crispy }}
                {% endfor %}
            {% else %}
                {{ wizard.form  | crispy }}
            {% endif %}
            {% if hours_form %}
                <div class="form-inline">
                {{ hours_form.management_form | crispy }}
                {% for form in hours_form.forms %}
                    {{ form  | crispy }}
                {% endfor %}
                </div>
            {% endif %}
            <button type="submit" id="submitBtn" class="form-control btn btn-block deca-register deca-light-button">Next Step</button>

    </div>

    </form>
    <script type="text/javascript">
        $('#registerForm input:checkbox').change(function() {
            if (this.checked){
                $("#submitBtn").text('Next Step');
            }
            else{
                $("#submitBtn").text('Submit');
            }
        }).change();
        $('#div_id_{{wizard.steps.step0}}-lab_machine_count').hide();
        $('#id_{{wizard.steps.step0}}-services').on('changed.bs.select', function(event, clickedIndex, newValue, oldValue){            
            if(newValue && this.options[clickedIndex].text.toLowerCase().includes('lab')){
                $('#div_id_{{wizard.steps.step0}}-lab_machine_count').fadeIn("slow");
            }
            else if(oldValue && this.options[clickedIndex].text.toLowerCase().includes('lab')){            
                $('#div_id_{{wizard.steps.step0}}-lab_machine_count').fadeOut("slow");
            }
        });
    </script>
{% endblock content %}

digital_inclusion/organization_management/templates/edit_organization.jinja2
{% extends "base.jinja2" %}
{% load widget_tweaks %}
{% block content %}


<form method="post" action="{% url "edit_organization" organization.pk %}">
  {% csrf_token %}
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {% render_field field class+="form-control" %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content%}

digital_inclusion/organization_management/templates/email_template.jinja2
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>You Have Been Invited to {{ organization.name }}'s DECA Site</title>
</head>
<body>
    <a href="">Click Here to Register!</a>
</body>
</html>

digital_inclusion/organization_management/templates/list_organizations.jinja2
{% extends "base.jinja2" %}

{% block content %}
      <div class="row p-4">
        <div class="col-md-1"></div>  
        <div class="col-md-10">
          <div>
            <h1 class="ml-2 pull-left">Organizations</h1>
            <a class="mr-3 btn btn-primary pull-right btn-lg" href="{% url 'orgs:wizard' %}" role="button">Add an organization</a>
          </div>
          <div class="table" data-example-id="simple-responsive-table">
            <div class="table-responsive">
              <!-- Table -->
              <table class="table table-striped" id="myTable">
                <thead>
                  <tr>
                    <th>Organization</th>
                    <th>Branch Address</th>
                    <th>Services Offered</th>
                    <th>Upcoming Event</th>
                    <th>Contact</th>
                  </tr>
                </thead>
                
                <tbody>
                {% for branch in branches %}
                  <tr onclick="window.location='{{branch.pk}}/';">
                    <td>{{branch.organization.name}}</td>
                    <td>{{branch.address}}</td>
                    <td>
                        {% for service in branch.services.all %}
                            {% if forloop.last %}
                                {{service.type}}
                            {% else %}
                                {{service.type}},
                            {% endif %}
                        {% empty %}
                            None
                        {% endfor %}
                    </td>
                    <td>No upcoming event</td>
                    <td>{{branch.contact_phone.as_national}}</td>
                  </tr>                  
                {% endfor %}
                </tbody>
              </table> 
            </div> <!-- end of <div class = "table-responsive"> -->
          </div> <!-- end of <div class = "table"> -->
        </div> <!-- end of <div class = "col-md-10"> -->
      </div> <!-- end of <div class = "row"> -->
    <script type="text/javascript">
        $(document).ready(function(){
            $('#myTable').DataTable(); 
        });
        </script>
        
        <script type="text/javascript">
        $(window).load(function() {
            $("#load").fadeOut();
            document.getElementById('myTable').style.visibility="visible";
        });
        </script>
{% endblock content %}