digital_inclusion/digital_inclusion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from organization_management import views
from main import urls as main_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("org/", include('organization_management.urls', namespace='orgs')),
    path("accounts/", include('user_management.urls')),
    path("flag/", include('flagging.urls', namespace='flags')),
    path("events/", include('events.urls', namespace='events')),
    path("search/", include('search.urls', namespace='search')),
] + main_urls.urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digital_inclusion/events/urls.py
from django.conf.urls import url
from events import views
from django.http import HttpRequest

app_name = "events"
urlpatterns = [
    url(r'add/$', views.add, name="add_event"),
    url(r'$', views.calendar, name="calendar"),
]

digital_inclusion/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'about/$', views.about, name="about"),
    url(r'map/$', views.map, name="map"),
    url(r'^$', views.index, name="index"),
]

digital_inclusion/events/models.py
from django.db import models
from organization_management.models import Organization

# Create your models here.
class Event(models.Model):
    organization = models.ForeignKey(Organization, on_delete="CASCADE", related_name="events")
    name = models.CharField(max_length=512)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    description = models.TextField(max_length=5096)
    mask_profile = models.BooleanField(default=False)
    contact_name = models.CharField(max_length=256)
    url = models.URLField(null=True, blank=True)

digital_inclusion/events/forms.py
from django import forms
from events.models import Event
from datetime import datetime
from django.contrib.admin import widgets

class EventInputForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['organization', 'name', 'start_time','end_time', 'description', 'mask_profile', 'contact_name', 'url']
        mask_profile = forms.Select(choices=("Yes", "No"))
        start_time = forms.DateTimeField(input_formats=["%Y/%m/%d %H:%M"])
        end_time = forms.DateTimeField(input_formats=["%Y/%m/%d %H:%M"])
        url = forms.URLField(required=False)
        labels = {
            'organization': 'Organization',
            'name': 'Name',
            'start_time': 'Event Start Time',
            'end_time': 'Event End Time',
            'description': 'Description',
            'mask_profile': 'Mask Profile?',
            'contact_name': 'Contact Name',
            'url': 'Event URL'
        }
        widgets = {
            'organization': forms.Select(attrs={'placeholder': 'Select Organization'}),
            'name': forms.TextInput(attrs={'placeholder': 'Event Name'}),
            # 'start_time': forms.DateTimeInput(format="%Y/%m/%d %H:%M"),
            # 'end_time': forms.DateTimeInput(format="%Y/%m/%d %H:%M"),
            # 'time': widgets.AdminSplitDateTime(),
            'description': forms.Textarea(attrs={'placeholder': 'Event Description'}),
            'contact_name': forms.TextInput(attrs={'placeholder': 'Name of contact'}),
            # 'url': forms.URLInput()
        }

digital_inclusion/events/views.py
import json

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from events.forms import EventInputForm
from organization_management.models import Organization
from events.models import Event
from django.http import HttpResponseRedirect


# Create your views here.


def add(request):
    if request.method == "POST":
        f = EventInputForm(request.POST)
        if f.is_valid():
            f.save()
            return HttpResponseRedirect("/events/")
    elif request.method == "GET":
        f = EventInputForm()
    return render(request,
                  template_name="event_input.jinja2",
                  context={"form": f})


def calendar(request):
    return render(request, template_name="calendar.jinja2", context={
        "events": Event.objects.all(),
        "event_widget_options": {
            "show_header": True,
            # "default_view": "listMonth"
        }
    })

digital_inclusion/digital_inclusion/templates/about.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='styles.css') }}">

    <title>DECA</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg extra-margin">
      <div class="row input-group">
        <div class="col-md-4">
          <img class="banner-img" src="{{ url_for('static',filename='banner_1024.png') }}" />
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="search-container">
            <input type="text" class="search-box" placeholder="Search...">
            <button class="btn-outline-secondary search-button" type="button">
                <i class="fa fa-search"></i>
            </button>
          </div>
          <div class="organization-login">
            <a class="nav-link" href="#">Log In</a>
          </div>
        </div>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg" style="background-color:#003a5c;">
       <ul class="nav navbar-nav mx-auto">
         <li class="nav-item">
           <a class="nav-link" href="#">Organizations</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">About</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Map</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Calendar</a>
         </li>
       </ul>
     </nav>
     <header>
      
     </header>

     <!-- Page Content -->
     <div class="container">

       <div class="purpose-section">
         <h1 class="my-4">About Digital Empowerment Community</h1>
         <div class="content">
          <div class="field field-name-body field-type-text-with-summary field-label-hidden">
            <div class="field-items">
            <div class="field-item even" property="content:encoded">
              <p>The Digital Empowerment Community of Austin (DECA) is a network of non-profits, educational instititions, and other stakeholders working together to improve our community's ability to participate in digital society, making a more digitally inclusive Austin.</p>
              <h3>What is Digital Inclusion?</h3>
              <p>Digital inclusion is the ability of individuals and groups to equally access and use information and communication technologies afordably, efficiently, and reliably along with digital training, resources, and skills needed to fully participate in  a digital society.</p>
              <h3>How We Started</h3>
              <p>DECA was officially convened on Thursday, October 29th, 2015 when more than 80 community stakeholders convened in the Asian American Resource Center to collaborate and brainstorm on challenges and opportunities in connecting our community. This meeting commenced Phase I of the co-creation strategy that developed a list of <a href="http://austintexas.gov/page/digital-inclusion-strategic-plan">short, medium, and long-term initiatives</a> that could have the highest impact on digital inclusion.</p>
              <p>Four working groups were convened to work towards problem identification and solution generation and implementation. The four working groups are linked at the bottom of the page.</p>
              <h3>Where We Are Today</h3>
              <p>The Train the Trainer working group has since evolved into what is now the Capacity working group. Throughout its evolution, the working group fostered a sense of community ownership and leadership with the effort of bringing awareness to digital inequities in Austin and opportunities that support digital inclusion.</p>
              <h3>Latest Information</h3>
              <ul>
                <li>Join our Google Group - <a href="mailto:Digital-Equity-ATX@googlegroups.com">Digital-Equity-ATX@googlegroups.com</a></li>
                <li>Subscribe to our Digital Inclusion Newsletter– <a href="http://www.eepurl.com/UUKMv">www.eepurl.com/UUKMv</a></li>
                <li>Attend our monthly DECA Meetings– <a href="mailto:jesse.rodriguez@austintexas.gov?subject=DECA%20Meeting%20Question&amp;body=Please%20include%20your%20name%20and%20contact%20information.">Contact Jesse Rodriguez</a>  for info on the next meeting</li>
                <li>Attend community events that promote digital inclusion
                  <ul>
                    <li><strong>Greater Austin STEM Networking Forum</strong> (April 11, 5:30-6pm, @ ACC Highland)</li>
                    <li><strong>Maker Faire Austin</strong> (May 5-6, 10am-6pm, @ Thinkery)</li>
                    <li><strong>ATX Hack4Change</strong> (June 1-3, @St. Edward's University)</li>
                  </ul>
                </li>
              </ul>
              <h3>Resources and Information</h3>
              <p><a href="https://airtable.com/shrZ9dEcKmoWYafBc">Capacity Working Group</a></p>
              <p><a href="https://airtable.com/shrLxIh7MVsW04V2a">Curriculum Standards Working Group</a></p>
              <p><a href="https://airtable.com/shrRsvhUL58km676i">Standard Client Survey Working Group </a></p>
              <p><a href="https://airtable.com/shrfZDYVQcMglxm2c">TechHire Working Group</a></p>
            </div>
            </div>
          </div>
        </div>
      </div>

     </div>
     <!-- /.container -->

     <!-- Footer -->
     <footer class="py-5 bg-dark">
       <div class="container">
         <p class="m-0 text-center text-white">Copyright &copy; Digital Empowerment Community of Austin 2018.</p>
       </div>
       <!-- /.container -->
     </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

digital_inclusion/digital_inclusion/templates/base.jinja2
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static "styles/main.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.0-beta/css/bootstrap-select.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" media="screen">
    <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.0-beta/js/bootstrap-select.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    {% block imports %} {% endblock imports %}
  <title>{% block title %}DECA{% endblock %}</title>
    {% block style %} {% endblock style %}
</head>

<body>
  <nav class="navbar navbar-expand-lg extra-margin">
    <div class="row input-group">
      <div class="col-md-4">
        <a href="{% url 'index' %}">
          <img class="banner-img" src="{% static "images/banner_1024.png" %}" />
        </a>
      </div>
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4">
        <div class="search-container">
          <input type="text" class="search-box" placeholder="Search...">
          <button class="btn-outline-secondary search-button" type="button">
            <a class="fa fa-search"></a>
          </button>
            <div class="autocomplete">
                <ul>
                    <li>Option1</li>
                    <li>Option2</li>
                    <li>Option3</li>
                    <li>Option4</li>
                </ul>
            </div>
        </div>
        <div class="organization-login">
          {% if request.user.is_authenticated %}
          <span>Welcome {{request.user.username}}! <a href="{% url 'logout' %}">logout</a></span>
          {% else %}
          <a class="nav-link" href="{% url 'login' %}">Log In</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  <nav class="navbar navbar-expand-lg" style="background-color:#003a5c;">
    <ul class="nav navbar-nav mx-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'orgs:index' %}">Organizations</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'map' %}">Map</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'events:calendar' %}">Calendar</a>
      </li>
    </ul>
  </nav>
  <div>
    {% block content %}{% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Digital Empowerment Community of Austin 2018.</p>
    </div>
    <!-- /.container -->
  </footer>
    {% block scripts %}
    {% endblock scripts %}
  <script>
      var isDown = false;

      $(".search-box").on("keyup", function(){
          if (!isDown){
              $(".autocomplete").slideDown({duration: 200});
              isDown = true
          }
          $(".autocomplete").load("/search/autocomplete?query=" + encodeURIComponent($(this).val()))
      })
      $(".search-box").on("blur", function(){
          $(".autocomplete").slideUp({duration: 200});
          isDown = false
      })
      $(".search-button").click(function(){
          window.open("/search?query=" + encodeURIComponent($(".search-box").val()))
      })
  </script>
</body>

</html>

digital_inclusion/digital_inclusion/templates/event_input.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='styles.css') }}">

    <title>DECA</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg extra-margin">
      <div class="row input-group">
        <div class="col-md-4">
          <img class="banner-img" src="{{ url_for('static',filename='banner_1024.png') }}" />
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="search-container">
            <input type="text" class="search-box" placeholder="Search...">
            <button class="btn-outline-secondary search-button" type="button">
                <i class="fa fa-search"></i>
            </button>
          </div>
          <div class="organization-login">
            <a class="nav-link" href="#">Log In</a>
          </div>
        </div>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg" style="background-color:#003a5c;">
       <ul class="nav navbar-nav mx-auto">
         <li class="nav-item">
           <a class="nav-link" href="#">Organizations</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">About</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Map</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Calendar</a>
         </li>
       </ul>
     </nav>
     <div class="container">
       <h1 class="formtitle">Submit a New Event</h1>
       <form id="eventInputForm" method="POST">
         <div class="form-group row">
           <label class= "col-sm-2 col-form-label">Organization: </label>
           <div class="col-sm-10">
             <select class="form-control" id="organization" name="organization">
               <option value="default" selected disabled hidden>Select your organization</option>
               <option>Org 1</option>
               <option>Org 2</option>
               <option>Org 3</option>
               <option value="/form">NON-REGISTERED ORGANIZATION</option>
             </select>
           </div>
         </div>
          <div class="form-group row">
            <label for="eventName" class="col-sm-2 col-form-label">Event Name:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="eventName" name="eventName" placeholder="Event Name">
            </div>
          </div>
          <div class="form-group row">
            <label for="eventDate" class="col-2 col-form-label">Date and Time of Event:</label>
            <div class="col-10">
              <input class="form-control" type="datetime-local" min='2017-06-14T00:00:00' name="eventDate" id="eventDate">
            </div>
          </div>
          <div class="form-group row">
            <label for="eventDescription" class="col-sm-2 col-form-label">Event Description:</label>
            <div class="col-sm-10">
              <textarea class="form-control" rows="5" name="eventDescription" id="eventDescription" placeholder="Event Description"></textarea>
            </div>
          </div>
          <fieldset class="form-group">
            <div class="row">
              <legend class="col-form-label col-sm-2 pt-0">Mask Profile?</legend>
              <div class="col-sm-10">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="gridRadio" id="radioNo" value="no" checked>
                  <label class="form-check-label" for="radioNo">
                    No
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="gridRadio" id="radioYes" value="yes">
                  <label class="form-check-label" for="radioYes">
                    Yes
                  </label>
                </div>
              </div>
            </div>
        </fieldset>
        <div style="text-align:center">
          <button type="submit" class="btn deca-register deca-light-button">Submit Event</button>
        </div>
    </form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
    <script src="{{ url_for('static',filename='event_input.js') }}"/></script>
  </body>
</html>

digital_inclusion/digital_inclusion/templates/events.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='styles.css') }}">

    <title>DECA</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg extra-margin">
      <div class="row input-group">
        <div class="col-md-4">
          <img class="banner-img" src="{{ url_for('static',filename='banner_1024.png') }}" />
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="search-container">
            <input type="text" class="search-box" placeholder="Search...">
            <button class="btn-outline-secondary search-button" type="button">
                <i class="fa fa-search"></i>
            </button>
          </div>
          <div class="organization-login">
            <a class="nav-link" href="#">Log In</a>
          </div>
        </div>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg" style="background-color:#003a5c;">
       <ul class="nav navbar-nav mx-auto">
         <li class="nav-item">
           <a class="nav-link" href="#">Organizations</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">About</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Map</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Calendar</a>
         </li>
       </ul>
     </nav>

     <!-- Page Content -->
       <div class="container" style="margin-top: 250px;">
         <div class="row">
           <div class="col-md-8">
             <div class="report-button">
               <button type="button" class="btn deca-dark-button" data-toggle="modal" data-target="#report">Report for Review</button>
               <!-- Modal -->
                 <div class="modal fade" id="report" tabindex="-1" role="dialog" aria-labelledby="eventLabel" aria-hidden="true">
                   <div class="modal-dialog" role="document">
                     <div class="modal-content">
                       <div class="modal-header">
                         <h5 class="modal-title" id="eventLabel" center>{{event_name}}</h5>
                         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                           <span aria-hidden="true">&times;</span>
                         </button>
                       </div>
                       <div class="modal-body">
                         <p>
                           {{description}}
                         </p>
                         <p>
                           <span style="font-weight: bold">Organization:</span> {{org_name}}
                         </p>
                         <p>
                           <span style="font-weight: bold">Contact:</span> {{contact_name}}
                         </p>
                         <p>
                           <span style="font-weight: bold">Event Date:</span> {{ value|date:"M d P" }}
                         </p>
                         <span style="float: right"><a href={{url}} class="btn deca-dark-button" target="_blank">More Info</a></button></span>
                       </div>
                       <div class="modal-footer">
                         <button type="button" class="btn deca-remove-button" data-dismiss="modal">Close</button>
                       </div>
                     </div>
                   </div>
                 </div>
             </div>
           </div>
         </div>
       </div>
     <!-- Footer -->
     <footer class="py-5 bg-dark">
       <div class="container">
         <p class="m-0 text-center text-white">Copyright &copy; Digital Empowerment Community of Austin 2018.</p>
       </div>
       <!-- /.container -->
     </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>