digital_inclusion/digital_inclusion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from organization_management import views
from main import urls as main_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("org/", include('organization_management.urls', namespace='orgs')),
    path("accounts/", include('user_management.urls')),
    path("flag/", include('flagging.urls', namespace='flags')),
    path("events/", include('events.urls', namespace='events')),
    path("search/", include('search.urls', namespace='search')),
] + main_urls.urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digital_inclusion/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'about/$', views.about, name="about"),
    url(r'map/$', views.map, name="map"),
    url(r'^$', views.index, name="index"),
]

digital_inclusion/organization_management/urls.py
from django.conf.urls import url
from organization_management import views

app_name = "organization_management"
urlpatterns = [
    url(r'wizard/', views.OrganizationWizard.as_view(), name="wizard"),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_organization, name='edit'),
    url(r'^(?P<pk>[0-9]+)/', views.view_organization, name='view'),    
    url(r'$', views.list_organization, name='index')    
]

digital_inclusion/main/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class UIComponent(models.Model):
    name = models.CharField(max_length=20, db_index=True)
    text = RichTextField()
    def __str__(self):
        return self.name

digital_inclusion/main/views.py
from django.shortcuts import render
from django.http import HttpRequest
from django.shortcuts import render
from django.conf import settings
from organization_management.models import Organization, Branch
from events.models import Event
from main.models import UIComponent

# Create your views here.
def index(request: HttpRequest):
    featured_orgs = Organization.objects.exclude(banner__isnull=True).exclude(banner__exact="").order_by("?")[:3]
    return render(request, template_name="index.jinja2",context={
        "events": Event.objects.all(),
        "event_widget_options": {
            "show_header": False,
            "default_view": "listMonth"
        },
        "featured_orgs": featured_orgs,
        "content": UIComponent.objects.get(name="Index Content"),
        "resources": UIComponent.objects.get(name="Index Resources"),
        "highlights": UIComponent.objects.get(name="Index Highlights"),
    })

def about(request: HttpRequest):
    return render(request, template_name="about.jinja2", context={"content": UIComponent.objects.get(name="About")})

def map(request: HttpRequest):
    return render(request, template_name="map.jinja2", context={
        "gmaps_api_key": settings.GOOGLE_MAPS_JS_API_KEY,
        "orgs": Branch.objects.all()
    })

digital_inclusion/main/templates/about.jinja2
{% extends "base.jinja2" %} {% load static %} {% block title %}DECA - About{% endblock %} {% block content %}
<div class="container">

    <div class="purpose-section">
        <div class="my-4">
            {{ content.text |safe }}
        </div>
    </div>

</div>
{% endblock %}

digital_inclusion/main/templates/index.jinja2
{% extends "base.jinja2" %}
{% load static %}
{% load staticfiles %}

{% block imports %}
    <script src="{% static 'moment.min.js' %}"></script>
    <script src="{% static 'fullcalendar.js' %}"></script>
{% endblock imports %}


{% block style %}
    <link rel="stylesheet" href="{% static 'fullcalendar.css' %}">
    <style>
        body {
            padding: 0;
            font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
            font-size: 14px;
        }

        {##calendar {#}
        {#    max-width: 900px;#}
        {#    margin: 0 auto;#}
        {
        #}#}
    </style>
{% endblock style %}
{% block content %}

    <header>

        {% if featured_orgs.all %}
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for org in featured_orgs.all %}
                {% if forloop.first %}
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                {% else %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}"></li>
                {% endif %}                
                {% endfor %}
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                {% for org in featured_orgs.all %}
                    {% if forloop.first %}
                        <div class="carousel-item active" style="background-image: url(/media/{{org.banner}})">
                    {% else %}
                        <div class="carousel-item" style="background-image: url(/media/{{org.banner}})">
                    {% endif %}
                        <div class="carousel-caption d-none d-md-block">
                            <h3>{{org.name}}</h3>
                            {% if org.branches.first %}
                            <a class="btn btn-info" href="{% url 'orgs:view' org.branches.first.pk %}">Visit Showcase</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        {% endif %}
    </header>

    <!-- Page Content -->
    <div class="container">

        <div class="purpose-section">
            <div class="my-4">
                {{ content.text |safe }}
            </div>
            <!-- Marketing Icons Section -->
        </div>

        <!-- Portfolio Section -->
        <div class="row">
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header card-center">Events</h4>
                    <div class="card-body">
                        <div id='calendar'></div>
                    </div>
                    <div class="card-footer card-center">
                        <a href="#" class="btn card-button">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header card-center">Highlights</h4>
                    <div class="card-body">
                        {{ highlights.text |safe }}
                    </div>
                    <div class="card-footer card-center">
                        <a href="#" class="btn card-button">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header card-center">Resources</h4>
                    <div class="card-body">
                        {{ resources.text |safe }}
                    </div>
                    <div class="card-footer card-center">
                        <a href="#" class="btn card-button">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
{% endblock %}
{% block scripts %}
    {% include 'event_widget.js.jinja2' %}

{% endblock scripts %}

digital_inclusion/main/templates/map.jinja2
{% extends "base.jinja2" %}
{% load static %}
{% block content %}
    <div class="container">
        <style>
            #map {
                height: 80vh;
                width: 100%;
            }
        </style>

        <div id="map"></div>
        <script>
            var map, infoWindow;
            String.prototype.format = function () {
                var i = 0, args = arguments;
                return this.replace(/{}/g, function () {
                    return typeof args[i] != 'undefined' ? args[i++] : '';
                });
            };
            var dat = [
                {% for org in orgs %}
                    {
                        id: "{{ org.id }}",
                        name: "{{ org.organization.name }}",
                        description: "{{ org.organization.description }}",
                        address: "{{ org.address }}",
                        website: "{{ org.organization.website }}",
                        {% if org.latitude is not none %}
                            lat: {{ org.latitude}},
                        {% else %}
                            lat: null,
                        {% endif %}
                        {% if org.longitude is not none %}
                            lng: {{ org.longitude}},
                        {% else %}
                            lng: null,
                        {% endif %}
                    },
                {% endfor %}
            ]


            var contentTemplate = "<div class='markerContent'>" +
                "<h2 class='markerTitle'>{}</h2> " +
                "<p class='markerDescription'>{}</p> " +
                "<a class='websiteMarker' href='{}' target='_blank'>Website</a>" +
                "<br>" +
                "<a class='profileMarker' href='/org/{}/' target='_blank'>Showcase</a>" +
                "<br>" +
                "<a href='https://www.google.com/maps?q={}' target='_blank'>Directions</a></div>";

            function initMap() {
                var atx = {lat: 30.267, lng: -97.743};
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 12,
                    center: atx,
                    styles: [{
                        "featureType": "all",
                        "elementType": "labels.text.fill",
                        "stylers": [{"color": "#ffffff"}]
                    }, {
                        "featureType": "all",
                        "elementType": "labels.text.stroke",
                        "stylers": [{"color": "#000000"}, {"lightness": 13}]
                    }, {
                        "featureType": "administrative",
                        "elementType": "geometry.fill",
                        "stylers": [{"color": "#000000"}]
                    }, {
                        "featureType": "administrative",
                        "elementType": "geometry.stroke",
                        "stylers": [{"color": "#144b53"}, {"lightness": 14}, {"weight": 1.4}]
                    }, {
                        "featureType": "landscape",
                        "elementType": "all",
                        "stylers": [{"color": "#08304b"}]
                    }, {
                        "featureType": "poi",
                        "elementType": "geometry",
                        "stylers": [{"color": "#0c4152"}, {"lightness": 5}]
                    }, {
                        "featureType": "road.highway",
                        "elementType": "geometry.fill",
                        "stylers": [{"color": "#000000"}]
                    }, {
                        "featureType": "road.highway",
                        "elementType": "geometry.stroke",
                        "stylers": [{"color": "#0b434f"}, {"lightness": 25}]
                    }, {
                        "featureType": "road.arterial",
                        "elementType": "geometry.fill",
                        "stylers": [{"color": "#000000"}]
                    }, {
                        "featureType": "road.arterial",
                        "elementType": "geometry.stroke",
                        "stylers": [{"color": "#0b3d51"}, {"lightness": 16}]
                    }, {
                        "featureType": "road.local",
                        "elementType": "geometry",
                        "stylers": [{"color": "#000000"}]
                    }, {
                        "featureType": "transit",
                        "elementType": "all",
                        "stylers": [{"color": "#146474"}]
                    }, {"featureType": "water", "elementType": "all", "stylers": [{"color": "#021019"}]}]
                });
                for (var i = 0; i < dat.length; i++) {
                    var org = dat[i];
                    var marker = new google.maps.Marker({
                        position: {lat: org["lat"], lng: org["lng"]},
                        title: org["name"],
                        map: map
                    })
                    var markerContent = contentTemplate.format(org["name"], org["description"], org["website"], org["id"], org["address"]);
                    marker['infowindow'] = new google.maps.InfoWindow({
                        content: markerContent
                    });
                    google.maps.event.addListener(marker, 'click', function () {
                        this['infowindow'].open(map, this);
                    });
                }

            }
        </script>
        <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ gmaps_api_key }}&callback=initMap">
        </script>


    </div>
    <!-- /.container -->

{% endblock %}