digital_inclusion/digital_inclusion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from organization_management import views
from main import urls as main_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("org/", include('organization_management.urls', namespace='orgs')),
    path("accounts/", include('user_management.urls')),
    path("flag/", include('flagging.urls', namespace='flags')),
    path("events/", include('events.urls', namespace='events')),
    path("search/", include('search.urls', namespace='search')),
] + main_urls.urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digital_inclusion/events/urls.py
from django.conf.urls import url
from events import views
from django.http import HttpRequest

app_name = "events"
urlpatterns = [
    url(r'add/$', views.add, name="add_event"),
    url(r'$', views.calendar, name="calendar"),
]

digital_inclusion/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'about/$', views.about, name="about"),
    url(r'map/$', views.map, name="map"),
    url(r'^$', views.index, name="index"),
]

digital_inclusion/events/models.py
from django.db import models
from organization_management.models import Organization

# Create your models here.
class Event(models.Model):
    organization = models.ForeignKey(Organization, on_delete="CASCADE", related_name="events")
    name = models.CharField(max_length=512)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    description = models.TextField(max_length=5096)
    mask_profile = models.BooleanField(default=False)
    contact_name = models.CharField(max_length=256)
    url = models.URLField(null=True, blank=True)

digital_inclusion/events/forms.py
from django import forms
from events.models import Event
from datetime import datetime
from django.contrib.admin import widgets

class EventInputForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['organization', 'name', 'start_time','end_time', 'description', 'mask_profile', 'contact_name', 'url']
        mask_profile = forms.Select(choices=("Yes", "No"))
        start_time = forms.DateTimeField(input_formats=["%Y/%m/%d %H:%M"])
        end_time = forms.DateTimeField(input_formats=["%Y/%m/%d %H:%M"])
        url = forms.URLField(required=False)
        labels = {
            'organization': 'Organization',
            'name': 'Name',
            'start_time': 'Event Start Time',
            'end_time': 'Event End Time',
            'description': 'Description',
            'mask_profile': 'Mask Profile?',
            'contact_name': 'Contact Name',
            'url': 'Event URL'
        }
        widgets = {
            'organization': forms.Select(attrs={'placeholder': 'Select Organization'}),
            'name': forms.TextInput(attrs={'placeholder': 'Event Name'}),
            # 'start_time': forms.DateTimeInput(format="%Y/%m/%d %H:%M"),
            # 'end_time': forms.DateTimeInput(format="%Y/%m/%d %H:%M"),
            # 'time': widgets.AdminSplitDateTime(),
            'description': forms.Textarea(attrs={'placeholder': 'Event Description'}),
            'contact_name': forms.TextInput(attrs={'placeholder': 'Name of contact'}),
            # 'url': forms.URLInput()
        }

digital_inclusion/events/views.py
import json

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from events.forms import EventInputForm
from organization_management.models import Organization
from events.models import Event
from django.http import HttpResponseRedirect


# Create your views here.


def add(request):
    if request.method == "POST":
        f = EventInputForm(request.POST)
        if f.is_valid():
            f.save()
            return HttpResponseRedirect("/events/")
    elif request.method == "GET":
        f = EventInputForm()
    return render(request,
                  template_name="event_input.jinja2",
                  context={"form": f})


def calendar(request):
    return render(request, template_name="calendar.jinja2", context={
        "events": Event.objects.all(),
        "event_widget_options": {
            "show_header": True,
            # "default_view": "listMonth"
        }
    })

digital_inclusion/events/templates/calendar.jinja2
{% extends "base.jinja2" %}
{% load staticfiles %}
{% block imports %}
    <script src="{% static 'moment.min.js' %}"></script>
    <script src="{% static 'fullcalendar.js' %}"></script>
{% endblock imports %}
{% block style %}
    <link rel="stylesheet" href="{% static 'fullcalendar.css' %}">
    <style>
        body {
            margin: 40px 10px;
            padding: 0;
            font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
            font-size: 14px;
        }

        #calendar {
            margin-top: 40px !important;
            max-width: 900px;
            margin: 0 auto;
        }

        #add_event_btn {
        {#float:right;#} clear: both;
            display: block;
        }
    </style>
{% endblock style %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'events:add_event' %}" class="btn btn-info" role="button" id="add_event_btn">Add Event</a>
    {% endif %}
    <div id='calendar'></div>

{% endblock content %}

{% block scripts %}
    {% include 'event_widget.js.jinja2' %}
{% endblock scripts %}

digital_inclusion/events/templates/event_input.jinja2
{% extends "base.jinja2" %}
{% load widget_tweaks %}
{% load static %}
{% block imports %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
{% endblock imports %}
{% block style %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'jquery.datetimepicker.css' %}">
{% endblock style %}
{% block content %}
    <div class="container">
        <h1 class="formtitle">Add an Event</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.organization.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.organization class+="form-control" %}
                </div>
                {% if form.organization.help_text %}
                    <small class="form-text text-muted">{{ form.organization.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.organization.errors %}
                    {% for error in form.organization.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.name.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.name class+="form-control" %}
                </div>
                {% if form.name.help_text %}
                    <small class="form-text text-muted">{{ form.name.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.start_time.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.start_time class+="form-control" %}
                </div>
                {% if form.start_time.help_text %}
                    <small class="form-text text-muted">{{ form.start_time.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.start_time.errors %}
                    {% for error in form.start_time.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.end_time.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.end_time class+="form-control" %}
                </div>
                {% if form.end_time.help_text %}
                    <small class="form-text text-muted">{{ form.end_time.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.end_time.errors %}
                    {% for error in form.end_time.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.description.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.description class+="form-control" %}
                </div>
                {% if form.description.help_text %}
                    <small class="form-text text-muted">{{ form.description.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.description.errors %}
                    {% for error in form.description.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.mask_profile.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.mask_profile class+="form-control" %}
                </div>
                {% if form.mask_profile.help_text %}
                    <small class="form-text text-muted">{{ form.mask_profile.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.mask_profile.errors %}
                    {% for error in form.mask_profile.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.contact_name.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.contact_name class+="form-control" %}
                </div>
                {% if form.contact_name.help_text %}
                    <small class="form-text text-muted">{{ form.contact_name.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.contact_name.errors %}
                    {% for error in form.contact_name.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{ form.url.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% render_field form.url class+="form-control" %}
                </div>
                {% if form.contact_name.help_text %}
                    <small class="form-text text-muted">{{ form.url.help_text }}</small>
                {% endif %}
            </div>
            <div class="row justify-content-end">
                {% if form.url.errors %}
                    {% for error in form.url.errors %}
                        <div class="col-sm-10">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="row justify-content-end" style="text-align:center">
                <div class="col-sm-10">
                    <button type="submit" class="form-control btn deca-register deca-light-button">Register</button>
                </div>
            </div>
        </form>

    </div>
{% endblock content %}

{% block scripts %}
    <script>
        {#$("#id_start_time").datepicker("option", "dateFormat", "'yyy-dd-mm HH:MM:ss");#}
        {#$("#id_end_time").datepicker("option", "dateFormat", "'yyy-dd-mm HH:MM:ss");        #}
        $("#id_start_time").datetimepicker({
            step:15,
            format:'Y-m-d H:m:s'
            {#inline:true#}
        });
        $("#id_end_time").datetimepicker({
            step:15,
            format:'Y-m-d H:m:s'
            {#inline:true#}
        });
    </script>
{% endblock scripts %}

digital_inclusion/events/templates/event_widget.js.jinja2
<script>
    var events = [
        {% for event in events %}
            {
                title: "{{ event.name}}",
                start: "{{ event.start_time|date:'Y-m-d H:m:s'}}",
                end: "{{ event.end_time |date:'Y-m-d H:m:s'}}",
                organization_name: "{{ event.organization.name }}",
                description: "{{ event.description }}",
                contact_name: "{{ event.contact_name }}",
                {% if event.url is not None %}
                    url: "{{ event.url }}"
                {% endif %}
            },
        {% endfor %}
    ]
    var txt = "{{ event_widget_options.show_header }}"
    $(document).ready(function () {
        var calendar = $('#calendar').fullCalendar({
        {% if event_widget_options.show_header %}
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay,listWeek'
            },
        {% endif %}
            defaultDate: new Date().toISOString().split('T')[0],
        {% if event_widget_options.default_view is not None %}
            defaultView: "{{  event_widget_options.default_view}}",
        {% endif %}
            navLinks: true, // can click day/week names to navigate views
            editable: false,
            eventLimit: true, // allow "more" link when too many events
            events: events,
            eventClick: function (calEvent, jsEvent, view) {

                {#alert('Event: ' + calEvent.title);#}
                {#alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);#}
                {#alert('View: ' + view.name);#}

                // change the border color just for fun
                {#$(this).css('border-color', 'red');#}
                jsEvent.preventDefault()
                console.log(calEvent)
                if (typeof calEvent.url != 'undefined' && calEvent.url != "None") {
                    window.open(calEvent.url, "_blank")
                }
            }
        });


    });
</script>

digital_inclusion/events/templates/events.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='styles.css') }}">

    <title>DECA</title>
</head>
<body>
<nav class="navbar navbar-expand-lg extra-margin">
    <div class="row input-group">
        <div class="col-md-4">
            <img class="banner-img" src="{{ url_for('static',filename='banner_1024.png') }}" />
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
            <div class="search-container">
                <input type="text" class="search-box" placeholder="Search...">
                <button class="btn-outline-secondary search-button" type="button">
                    <i class="fa fa-search"></i>
                </button>
            </div>
            <div class="organization-login">
                <a class="nav-link" href="#">Log In</a>
            </div>
        </div>
    </div>
</nav>
<nav class="navbar navbar-expand-lg" style="background-color:#003a5c;">
    <ul class="nav navbar-nav mx-auto">
        <li class="nav-item">
            <a class="nav-link" href="#">Organizations</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Map</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Calendar</a>
        </li>
    </ul>
</nav>

<!-- Page Content -->
<div class="container" style="margin-top: 250px;">
    <div class="row">
        <div class="col-md-8">
            <div class="report-button">
                <button type="button" class="btn deca-dark-button" data-toggle="modal" data-target="#report">Report for Review</button>
                <!-- Modal -->
                <div class="modal fade" id="report" tabindex="-1" role="dialog" aria-labelledby="eventLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="eventLabel" center>{{event_name}}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>
                                    {{description}}
                                </p>
                                <p>
                                    <span style="font-weight: bold">Organization:</span> {{org_name}}
                                </p>
                                <p>
                                    <span style="font-weight: bold">Contact:</span> {{contact_name}}
                                </p>
                                <p>
                                    <span style="font-weight: bold">Event Date:</span> {{ value|date:"M d P" }}
                                </p>
                                <span style="float: right"><a href={{url}} class="btn deca-dark-button" target="_blank">More Info</a></button></span>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn deca-remove-button" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Digital Empowerment Community of Austin 2018.</p>
    </div>
    <!-- /.container -->

</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>